# Generated by Django 5.2.3 on 2025-06-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexample',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_examples', to='problems.problem'),
        ),
    ]
