# Generated by Django 5.2.3 on 2025-07-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
