# Generated by Django 5.2.3 on 2025-07-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_data_file',
            field=models.FileField(upload_to='testcases/inputs'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_data_file',
            field=models.FileField(upload_to='testcases/outputs'),
        ),
    ]
