# Generated by Django 5.2.3 on 2025-07-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_testcase_input_data_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_data_file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_data_file',
            field=models.CharField(max_length=255),
        ),
    ]
