# Generated by Django 5.2.3 on 2025-06-25 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0002_problem_input_format_problem_output_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('py', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C')], max_length=4)),
                ('code', models.TextField()),
                ('user_input_data', models.TextField(blank=True, null=True)),
                ('user_output_data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_submissions', to='problems.problem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
