# Generated by Django 5.2.3 on 2025-06-26 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_input_format_problem_output_format_and_more'),
        ('submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmodel',
            name='verdict',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Runtime Error', 'Runtime Error'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='user_output_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CodeSaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('py', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C')], max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_code_saves', to='problems.problem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_code_saves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
