# Generated by Django 5.2.3 on 2025-06-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_alter_codesavemodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionmodel',
            name='user_input_data',
        ),
        migrations.RemoveField(
            model_name='submissionmodel',
            name='user_output_data',
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='verdict',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Runtime Error', 'Runtime Error'), ('Compilation Error', 'Compilation Error'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded')], max_length=100, null=True),
        ),
    ]
