# Generated by Django 5.2.3 on 2025-07-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_remove_submissionmodel_user_input_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesavemodel',
            name='memory_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesavemodel',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
