# Generated by Django 5.2.3 on 2025-07-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_codesavemodel_memory_taken_codesavemodel_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesavemodel',
            name='memory_taken',
        ),
        migrations.RemoveField(
            model_name='codesavemodel',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='submissionmodel',
            name='memory_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionmodel',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
